#!/usr/bin/with-contenv bash

GENERATED_SECRET="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
PARAM_FILE="/config/satisfy/parameters.yml"
SATIS_FILE="/config/satisfy/satis.json"

: ${SECRET:=$GENERATED_SECRET}
: ${ADMIN_AUTH:=false}
: ${ADMIN_USERS:=\~}

: ${REPO_NAME:=company/private-repository}
: ${HOMEPAGE:=http://localhost:8080}

: ${SSH_PRIVATE_KEY:=unset}
: ${REPO_DOMAIN_LIST:=github.com gitee.com bitbucket.org gitlab.com}

: ${CRON_ENABLED:=true}

USER_HOME=/config

# make our folders
mkdir -p /config/satisfy

# check for config and make default if needed
if [[ ! -e ${PARAM_FILE} ]]; then
  cat >${PARAM_FILE} <<EOF
parameters:
  secret: "${SECRET}"
  satis_filename: "%kernel.project_dir%/satis.json"
  satis_log_path: "%kernel.project_dir%/var/satis"
  admin.auth: ${ADMIN_AUTH}
  admin.users: ${ADMIN_USERS}
  composer.home: "%kernel.project_dir%/var/composer"
  github.secret: "${SECRET}"
  gitlab.secret: "${SECRET}"
EOF
fi

if [[ ! -e ${SATIS_FILE} ]]; then
  cat >${SATIS_FILE} <<EOF
{
    "name": "${REPO_NAME}",
    "homepage": "${HOMEPAGE}",
    "output-dir": "public",
    "output-html": true,
    "require-all": false,
    "require-dependencies": false,
    "require-dev-dependencies": false,
    "require-dependency-filter": true,
    "repositories": [
    ],
    "minimum-stability": "dev",
    "providers": false,
    "pretty-print": true
}
EOF
fi

# create satisfy config symlinks

symlinks=( \
${APP_ROOT}/satis.json \
${APP_ROOT}/config/parameters.yml
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/satisfy/"$(basename "$i")" "$i"
done

# SSH
if [[ ! -e ${USER_HOME}/.ssh ]]; then
  mkdir ${USER_HOME}/.ssh
  chown ${APP_USER}:${APP_USER} ${USER_HOME}/.ssh
  chmod 700 ${USER_HOME}/.ssh
fi

if [[ "${SSH_PRIVATE_KEY}" != "unset" ]] && [[ ! -e ${USER_HOME}/.ssh/id_rsa ]]; then
  echo "${SSH_PRIVATE_KEY}" > ${USER_HOME}/.ssh/id_rsa
  chmod 400 ${USER_HOME}/.ssh/id_rsa
fi

for _DOMAIN in ${REPO_DOMAIN_LIST} ; do
  IFS=':' read -a arr <<< "${_DOMAIN}"
  if [[ "${#arr[@]}" == "2" ]]; then
      port="${arr[1]}"
      ssh-keyscan -t rsa,dsa -p "${port}" ${arr[0]} >> ${USER_HOME}/.ssh/known_hosts
  else
      ssh-keyscan -t rsa,dsa ${_DOMAIN} >> ${USER_HOME}/.ssh/known_hosts
  fi
done

# crontab
[[ ! -f "/config/cron" ]] && \
	cp /defaults/cron /config/cron

if [[ "${CRON_ENABLED}" == "true" ]]; then
  crontab -u abc /config/cron
fi

# permissions
echo "Setting permissions"
chown -R abc:abc \
	/app \
	/config \
	/var/www/


if [ "$LOG_FILE" = "true" ]; then
  crontab -u abc /defaults/duckcron
  echo "log will be output to file"
else
  echo "log will be output to docker log"
fi